<a href="https://colab.research.google.com/github/Anisha-singh2207/machine-learning-maths/blob/main/Matrix%20Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import numpy as np

Creating numpy as np

In [43]:
matrix_1=np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [45]:
matrix_1.shape

(2, 2)

In [46]:
matrix_2=np.array([[10,35,45],[50,67,90],[90,45,67]])
print(matrix_2)

[[10 35 45]
 [50 67 90]
 [90 45 67]]


In [47]:
matrix_2.shape

(3, 3)

Creating matrices with random values

In [48]:
random_matrix=np.random.rand(3,3)
print(random_matrix)

[[0.85044306 0.31184481 0.80020161]
 [0.73714473 0.74682744 0.66435947]
 [0.73671962 0.55975798 0.11855645]]


In [49]:
# creating matricses iwth random integers
random_integer_matrix=np.random.randint(100,size=(5,5))
print(random_integer_matrix)

[[16 20 93 44 65]
 [27 43 17 60 50]
 [89 87 39 44 11]
 [ 4 97 73 65 85]
 [50 42  8 98  1]]


Matrix with all values as 1

In [57]:
matrix_3=np.ones((2,3),dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


Numm matrix or zero matrix

In [58]:
null_matrix=np.zeros((3,3),dtype=int)
print(null_matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Identity matrix

In [59]:
identity_matrix=np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [60]:
identity_matrix=np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Transpose of a matrix

In [61]:
# matyrix with random integer values
a=np.random.randint(100,size=(4,5))
print(a)

[[18 54 17  4 26]
 [97 18 35 54 35]
 [22 69 89 64 99]
 [58 23 37 24 48]]


In [62]:
transpose_of_a=np.transpose(a)
print(transpose_of_a)

[[18 97 22 58]
 [54 18 69 23]
 [17 35 89 37]
 [ 4 54 64 24]
 [26 35 99 48]]


Two matrices can be added only if they have the same shape

Matrix Addition

In [63]:
# creating two matrices
A=np.array([[2,3],[4,5]])
B=np.array([[6,7],[8,9]])
print(A)

[[2 3]
 [4 5]]


In [64]:
print(B)

[[6 7]
 [8 9]]


In [65]:
A.shape

(2, 2)

In [66]:
B.shape

(2, 2)

In [67]:
sum=A+B
print(sum)

[[ 8 10]
 [12 14]]


In [68]:
# creating two matrices with random values
matrix_1=np.random.randint(100,size=(3,3))
matrix_2=np.random.randint(100,size=(3,3))
print(matrix_1)

[[43 27 78]
 [83 65 94]
 [61 61 33]]


In [69]:
print(matrix_2)

[[ 3 95 88]
 [23 14 87]
 [ 0 19 71]]


In [70]:
sum=np.add(matrix_1,matrix_2)
print(sum)

[[ 46 122 166]
 [106  79 181]
 [ 61  80 104]]


Matrix subtraction

In [71]:
A=np.array([[2,3],[4,5]])
B=np.array([[6,7],[8,9]])

In [73]:
difference=A-B
print(difference)

[[-4 -4]
 [-4 -4]]


In [74]:
matrix_1=np.random.randint(100,size=(3,3))
matrix_2=np.random.randint(100,size=(3,3))
print( matrix_1)

[[97 81 57]
 [70 43 70]
 [65 14 60]]


In [75]:
print(matrix_2)

[[69 40 41]
 [46 27 44]
 [82 50  0]]


In [76]:
diff=np.subtract(matrix_1,matrix_2)
print(diff)

[[ 28  41  16]
 [ 24  16  26]
 [-17 -36  60]]


Multiplying a matrix by a scalar

In [77]:
x=5
y=np.random.randint(100,size=(3,3))
print(y)

[[27  0 11]
 [ 4 79 63]
 [73  9 42]]


In [78]:
product=np.multiply(x,y)
print(product)

[[135   0  55]
 [ 20 395 315]
 [365  45 210]]


Multiplying two matrices

In [80]:
matrix_1=np.random.randint(100,size=(3,3))
matrix_2=np.random.randint(100,size=(3,4))
print(matrix_1)


[[85  7  2]
 [38 87 26]
 [35 43 44]]


In [81]:
print(matrix_2)

[[43 54 77 24]
 [82 31 28 91]
 [86  5 11 39]]


In [82]:
product=np.dot(matrix_1,matrix_2)
print(product)

[[ 4401  4817  6763  2755]
 [11004  4879  5648  9843]
 [ 8815  3443  4383  6469]]


In [83]:
product.shape

(3, 4)

**Element wise matrix multiplication**

In [87]:
matrix_1=np.random.randint(100,size=(3,3))
matrix_2=np.random.randint(100,size=(3,3))
print(matrix_1)

[[76 55 44]
 [44 84 86]
 [63 47 41]]


In [88]:
print(matrix_2)

[[49  6 54]
 [40 20 15]
 [16 74 27]]


In [89]:
product=np.multiply(matrix_1,matrix_2)
print(product)

[[3724  330 2376]
 [1760 1680 1290]
 [1008 3478 1107]]
